DELETE FROM tblKeyWordDetail;
DELETE FROM tblKeyWord;
DELETE FROM tblActorDetail;
DELETE FROM tblActor;
DELETE FROM tblGenreDetail;
DELETE FROM tblGenre;
DELETE FROM tblWriterDetail;
DELETE FROM tblWriter;
DELETE FROM tblAwardDetail;
DELETE FROM tblAwardResult;
DELETE FROM tblAwardCategoryDesc;
DELETE FROM tblAwardType;
DELETE FROM tblReview;
DELETE FROM tblCritic;
DELETE FROM tblCriticClass;
DELETE FROM tblMovie;
DELETE FROM tblDirector;
DELETE FROM tblMPAA;

COMMIT;

PAUSE Existing data deleted... Press [Enter]

INSERT INTO tblKeyword VALUES (1,'Chase');
INSERT INTO tblKeyword VALUES (2,'Oklahoma');
INSERT INTO tblKeyword VALUES (3,'Waitress');
INSERT INTO tblKeyword VALUES (4,'Hell');
INSERT INTO tblKeyword VALUES (5,'Satanic Cult');
INSERT INTO tblKeyword VALUES (6,'Agent');
INSERT INTO tblKeyword VALUES (7,'CIA');
INSERT INTO tblKeyword VALUES (8,'France');
INSERT INTO tblKeyword VALUES (9,'Prostitution');
INSERT INTO tblKeyword VALUES (10,'Albanian');
INSERT INTO tblKeyword VALUES (11,'Pizza Delivery');
INSERT INTO tblKeyword VALUES (12,'Heist');
INSERT INTO tblKeyword VALUES (13,'Scheme');
INSERT INTO tblKeyword VALUES (14,'Pizza Delivery Boy');
INSERT INTO tblKeyword VALUES (15,'Invasion');
INSERT INTO tblKeyword VALUES (16,'General');
INSERT INTO tblKeyword VALUES (17,'Killed In Action');

PAUSE Keywords and phrases data complete... Press [Enter]

INSERT INTO tblCriticClass VALUES (1,'Critic');
INSERT INTO tblCriticClass VALUES (2,'User');


DELETE FROM tblCritic;
INSERT INTO tblCritic VALUES (1,'','','User1',2);
INSERT INTO tblCritic VALUES (2,'','','User2',2);
INSERT INTO tblCritic VALUES (3,'','','User3',2);
INSERT INTO tblCritic VALUES (4,'','','User4',2);
INSERT INTO tblCritic VALUES (5,'','','User5',2);
INSERT INTO tblCritic VALUES (6,'','','User6',2);
INSERT INTO tblCritic VALUES (7,'','','User7',2);
INSERT INTO tblCritic VALUES (8,'','','User8',2);
INSERT INTO tblCritic VALUES (9,'','','User9',2);
INSERT INTO tblCritic VALUES (10,'','','User10',2);
INSERT INTO tblCritic VALUES (11,'','','User11',2);
INSERT INTO tblCritic VALUES (12,'','','User12',2);
INSERT INTO tblCritic VALUES (13,'','','User13',2);
INSERT INTO tblCritic VALUES (14,'','','User14',2);
INSERT INTO tblCritic VALUES (15,'','','User15',2);
INSERT INTO tblCritic VALUES (16,'','','User16',2);
INSERT INTO tblCritic VALUES (17,'','','User17',2);
INSERT INTO tblCritic VALUES (18,'','','User18',2);
INSERT INTO tblCritic VALUES (19,'','','User19',2);
INSERT INTO tblCritic VALUES (20,'','','User20',2);
INSERT INTO tblCritic VALUES (21,'','','User21',2);
INSERT INTO tblCritic VALUES (22,'','','User22',2);
INSERT INTO tblCritic VALUES (23,'','','User23',2);
INSERT INTO tblCritic VALUES (24,'','','User24',2);
INSERT INTO tblCritic VALUES (25,'','','User25',2);
INSERT INTO tblCritic VALUES (26,'','','User26',2);
INSERT INTO tblCritic VALUES (27,'','','User27',2);
INSERT INTO tblCritic VALUES (28,'Roger','Ebert','',1);
INSERT INTO tblCritic VALUES (29,'Peter','Travers','',1);
INSERT INTO tblCritic VALUES (30,'Stephanie','Zacharek','',1);
INSERT INTO tblCritic VALUES (31,'Mick','LaSalle','',1);
INSERT INTO tblCritic VALUES (32,'Claude','Puig','',1);
INSERT INTO tblCritic VALUES (33,'','','Screen It!',1);
INSERT INTO tblCritic VALUES (34,'','','Urban Cinefile',1);
INSERT INTO tblCritic VALUES (35,'','','FlickFile',1);
INSERT INTO tblCritic VALUES (36,'Jennifer','Fallon','',1);

PAUSE Critic data complete... Press [Enter]

INSERT INTO tblGenre VALUES (1,'Action');
INSERT INTO tblGenre VALUES (2,'Comedy');
INSERT INTO tblGenre VALUES (3,'Family');
INSERT INTO tblGenre VALUES (4,'History');
INSERT INTO tblGenre VALUES (5,'Mystery');
INSERT INTO tblGenre VALUES (6,'Sci-Fi');
INSERT INTO tblGenre VALUES (7,'War');
INSERT INTO tblGenre VALUES (8,'Adventure');
INSERT INTO tblGenre VALUES (9,'Crime');
INSERT INTO tblGenre VALUES (10,'Fantasy');
INSERT INTO tblGenre VALUES (11,'Horror');
INSERT INTO tblGenre VALUES (12,'News');
INSERT INTO tblGenre VALUES (13,'Sport');
INSERT INTO tblGenre VALUES (14,'Western');
INSERT INTO tblGenre VALUES (15,'Animation');
INSERT INTO tblGenre VALUES (16,'Documentary');
INSERT INTO tblGenre VALUES (17,'Film-Noir');
INSERT INTO tblGenre VALUES (18,'Musical');
INSERT INTO tblGenre VALUES (19,'Biography');
INSERT INTO tblGenre VALUES (20,'Romance');
INSERT INTO tblGenre VALUES (21,'Thriller');
INSERT INTO tblGenre VALUES (22,'Drama');

PAUSE Genre data complete... Press [Enter]

INSERT INTO tblAwardType VALUES (1,'Academy of Motion Picture Arts and Sciences','Oscar');
INSERT INTO tblAwardType VALUES (2,'Academy of Science Fiction, Fantasy, and Horror Films','Saturn');
INSERT INTO tblAwardType VALUES (3,'Genie','');
INSERT INTO tblAwardType VALUES (4,'American Film Institute','AFI');
INSERT INTO tblAwardType VALUES (5,'Golden Raspberry Award','Razzie');
INSERT INTO tblAwardType VALUES (6,'Toronto International Film Festival','TIFF');
INSERT INTO tblAwardType VALUES (7,'Sundance Film Festival','');
INSERT INTO tblAwardType VALUES (8,'Art Directors Guild','');
INSERT INTO tblAwardType VALUES (9,'Directors Guild of America','');
INSERT INTO tblAwardType VALUES (10,'Hollywood Foreign Press Association','Golden Globe');
INSERT INTO tblAwardType VALUES (11,'International Animated Film Society','Annie');
INSERT INTO tblAwardType VALUES (12,'Screen Actors Guild','');
INSERT INTO tblAwardType VALUES (13,'Nickelodeon','Kid''s Choice Awards');
INSERT INTO tblAwardType VALUES (14,'Fox','Teen Choice Awards');
INSERT INTO tblAwardType VALUES (15,'Procter and Gamble','People''s Choice Awards');
INSERT INTO tblAwardType VALUES (16,'BMI Film and TV','');
INSERT INTO tblAwardType VALUES (17,'Austin Fantastic Fest','');
INSERT INTO tblAwardType VALUES (18,'Chicago International Film Festival','');
INSERT INTO tblAwardType VALUES (19,'Toronto After Dark Film Festival','');
INSERT INTO tblAwardType VALUES (20,'NCLR Alma','');
INSERT INTO tblAwardType VALUES (21,'Empire Awards - UK','');
INSERT INTO tblAwardType VALUES (22,'Hugo Awards','');
INSERT INTO tblAwardType VALUES (23,'MTV Movie Awards','');
INSERT INTO tblAwardType VALUES (24,'Phoenix Film Critics Society','');
INSERT INTO tblAwardType VALUES (25,'Visual Effects Society Awards','');
INSERT INTO tblAwardType VALUES (26,'Science Fiction and Fantasy Writers of America','');
INSERT INTO tblAwardType VALUES (27,'Broadcast Film Critics Association Awards','Critics Choice Awards');

PAUSE Award type data complete... Press [Enter]

INSERT INTO tblAwardCategoryDesc VALUES (1,'Favorite Movie',13);
INSERT INTO tblAwardCategoryDesc VALUES (2,'Favorite Movie Actor',13);
INSERT INTO tblAwardCategoryDesc VALUES (3,'Favorite Movie Actress',13);
INSERT INTO tblAwardCategoryDesc VALUES (4,'Hall of Fame Award',13);
INSERT INTO tblAwardCategoryDesc VALUES (5,'Wannabe Award',13);
INSERT INTO tblAwardCategoryDesc VALUES (6,'Cutest Couple',13);
INSERT INTO tblAwardCategoryDesc VALUES (7,'Favorite Animated Movie',13);
INSERT INTO tblAwardCategoryDesc VALUES (8,'Favorite Voice from an Animated Movie',13);
INSERT INTO tblAwardCategoryDesc VALUES (9,'Favorite Buttkicker',13);
INSERT INTO tblAwardCategoryDesc VALUES (10,'Choice Movie: Action',14);
INSERT INTO tblAwardCategoryDesc VALUES (11,'Choice Movie: Action Actor',14);
INSERT INTO tblAwardCategoryDesc VALUES (12,'Choice Movie: Action Actress',14);
INSERT INTO tblAwardCategoryDesc VALUES (13,'Choice Movie: Drama',14);
INSERT INTO tblAwardCategoryDesc VALUES (14,'Choice Movie: Drama Actor',14);
INSERT INTO tblAwardCategoryDesc VALUES (15,'Choice Movie: Drama Actress',14);
INSERT INTO tblAwardCategoryDesc VALUES (16,'Choice Movie: Romantic Comedy',14);
INSERT INTO tblAwardCategoryDesc VALUES (17,'Choice Movie: Romantic Comedy Actor',14);
INSERT INTO tblAwardCategoryDesc VALUES (18,'Choice Movie: Romantic Comedy Actress',14);
INSERT INTO tblAwardCategoryDesc VALUES (19,'Choice Movie: Thriller',14);
INSERT INTO tblAwardCategoryDesc VALUES (20,'Choice Movie: Thriller Actor',14);
INSERT INTO tblAwardCategoryDesc VALUES (21,'Choice Movie: Thriller Actress',14);
INSERT INTO tblAwardCategoryDesc VALUES (22,'Choice Movie: Comedy',14);
INSERT INTO tblAwardCategoryDesc VALUES (23,'Choice Movie: Comedy Actor',14);
INSERT INTO tblAwardCategoryDesc VALUES (24,'Choice Movie: Comedy Actress',14);
INSERT INTO tblAwardCategoryDesc VALUES (25,'Choice Movie: Fantasy',14);
INSERT INTO tblAwardCategoryDesc VALUES (26,'Choice Movie: Fantasy Actor',14);
INSERT INTO tblAwardCategoryDesc VALUES (27,'Choice Movie: Fantasy Actress',14);
INSERT INTO tblAwardCategoryDesc VALUES (28,'Choice Movie: Sci-Fi',14);
INSERT INTO tblAwardCategoryDesc VALUES (29,'Choice Movie: Sci-Fi Actor',14);
INSERT INTO tblAwardCategoryDesc VALUES (30,'Choice Movie: Sci-Fi Actress',14);
INSERT INTO tblAwardCategoryDesc VALUES (31,'Choice Movie: Breakout Male',14);
INSERT INTO tblAwardCategoryDesc VALUES (32,'Choice Movie: Breakout Female',14);
INSERT INTO tblAwardCategoryDesc VALUES (33,'Choice Movie: Chemistry',14);
INSERT INTO tblAwardCategoryDesc VALUES (34,'Choice Movie: Liplock',14);
INSERT INTO tblAwardCategoryDesc VALUES (35,'Choice Movie: Fight',14);
INSERT INTO tblAwardCategoryDesc VALUES (36,'Choice Movie: Villain',14);
INSERT INTO tblAwardCategoryDesc VALUES (37,'Choice Movie: Animated',14);
INSERT INTO tblAwardCategoryDesc VALUES (38,'Choice Movie: Hissy Fit',14);
INSERT INTO tblAwardCategoryDesc VALUES (39,'Best Science Fiction Film',2);
INSERT INTO tblAwardCategoryDesc VALUES (40,'Best Fantasy Film',2);
INSERT INTO tblAwardCategoryDesc VALUES (41,'Best Horror-Thriller Film',2);
INSERT INTO tblAwardCategoryDesc VALUES (42,'Best Action-Adventure Film',2);
INSERT INTO tblAwardCategoryDesc VALUES (43,'Best Actor',2);
INSERT INTO tblAwardCategoryDesc VALUES (44,'Best Actress',2);
INSERT INTO tblAwardCategoryDesc VALUES (45,'Best Supporting Actor',2);
INSERT INTO tblAwardCategoryDesc VALUES (46,'Best Supporting Actress',2);
INSERT INTO tblAwardCategoryDesc VALUES (47,'Best Performance by a Younger Actor',2);
INSERT INTO tblAwardCategoryDesc VALUES (48,'Best Director',2);
INSERT INTO tblAwardCategoryDesc VALUES (49,'Best Writing',2);
INSERT INTO tblAwardCategoryDesc VALUES (50,'Best Music',2);
INSERT INTO tblAwardCategoryDesc VALUES (51,'Best Production Design',2);
INSERT INTO tblAwardCategoryDesc VALUES (52,'Best Editing',2);
INSERT INTO tblAwardCategoryDesc VALUES (53,'Best Costume',2);
INSERT INTO tblAwardCategoryDesc VALUES (54,'Best Make-Up',2);
INSERT INTO tblAwardCategoryDesc VALUES (55,'Best Special Effects',2);
INSERT INTO tblAwardCategoryDesc VALUES (56,'Best International Film',2);
INSERT INTO tblAwardCategoryDesc VALUES (57,'Best Animated Film',2);
INSERT INTO tblAwardCategoryDesc VALUES (58,'BMI Film Music',16);
INSERT INTO tblAwardCategoryDesc VALUES (60,'Best Horror Film (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (61,'Best Sci-Fi Film (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (62,'Best Action Film (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (63,'Best Comedy (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (64,'Best Director (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (65,'Best Screenplay (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (66,'Best Canadian Feature Film (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (67,'Best Leading Actor (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (68,'Best Leading Actress (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (69,'Best Ensemble Cast (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (70,'Best Make-Up (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (71,'Best Special Effects (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (72,'Best Soundtrack (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (73,'Best Cinematography (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (74,'Best Editing (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (75,'Best Trailer (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (76,'Best Poster (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (77,'Best Title Sequence (Fan Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (78,'Best Feature Film (Audience Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (79,'Best Canadian Short Film (Audience Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (80,'Best International Short Film (Audience Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (81,'Best Film to Watch with a Crowd (Audience Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (82,'Film Most Like to See a Sequel To (Audience Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (83,'Best Villain (Audience Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (84,'Best Hero (Audience Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (85,'Best Antihero (Audience Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (86,'Best Kill (Audience Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (87,'Best Fight (Audience Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (88,'Goriest Film (Audience Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (89,'Scariest Film (Audience Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (90,'Most Innovative Film (Audience Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (91,'Most Disturbing Film (Audience Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (92,'Most Thrilling Film (Audience Choice)',19);
INSERT INTO tblAwardCategoryDesc VALUES (93,'After Dark Competition (Silver Hugo)',18);
INSERT INTO tblAwardCategoryDesc VALUES (94,'Best Actor - Feature (Horror Jury)',17);
INSERT INTO tblAwardCategoryDesc VALUES (95,'Favorite Movie',20);
INSERT INTO tblAwardCategoryDesc VALUES (96,'Favorite Movie Actress - Drama/Adventure',20);
INSERT INTO tblAwardCategoryDesc VALUES (97,'Best Sci-Fi/Fantasy',21);
INSERT INTO tblAwardCategoryDesc VALUES (98,'Best Dramatic Presentation - Long Form',22);
INSERT INTO tblAwardCategoryDesc VALUES (99,'Best Hero',23);
INSERT INTO tblAwardCategoryDesc VALUES (100,'Best Original Song',24);
INSERT INTO tblAwardCategoryDesc VALUES (101,'Fantasy Film - Excellence in Production Design',8);
INSERT INTO tblAwardCategoryDesc VALUES (102,'Choice Summer Movie',14);
INSERT INTO tblAwardCategoryDesc VALUES (103,'Choice Summer Movie Star: Male',14);
INSERT INTO tblAwardCategoryDesc VALUES (104,'Choice Summer Movie Star: Female',14);
INSERT INTO tblAwardCategoryDesc VALUES (105,'Outstanding Composting in a Feature Motion Picture',25);
INSERT INTO tblAwardCategoryDesc VALUES (106,'Outstanding Visual Effects in a Visual Effects Driven Feature Motion Picture',25);
INSERT INTO tblAwardCategoryDesc VALUES (107,'Ray Bradbury Award',26);
INSERT INTO tblAwardCategoryDesc VALUES (108,'Best Comedy Movie',27);
INSERT INTO tblAwardCategoryDesc VALUES (109,'Favorite Comedy Movie',15);
INSERT INTO tblAwardCategoryDesc VALUES (110,'Favorite On Screen Team',15);
INSERT INTO tblAwardCategoryDesc VALUES (111,'Worst Actor',5);
INSERT INTO tblAwardCategoryDesc VALUES (112,'Worst Screen Couple',5);
INSERT INTO tblAwardCategoryDesc VALUES (113,'Best Cinematography',1);
INSERT INTO tblAwardCategoryDesc VALUES (114,'Best Director',1);
INSERT INTO tblAwardCategoryDesc VALUES (115,'Best Effects, Sound Effects Editing',1);
INSERT INTO tblAwardCategoryDesc VALUES (116,'Best Film Editing',1);
INSERT INTO tblAwardCategoryDesc VALUES (117,'Best Sound',1);
INSERT INTO tblAwardCategoryDesc VALUES (118,'Best Actor in a Leading Role',1);
INSERT INTO tblAwardCategoryDesc VALUES (119,'Best Art Direction-Set Decoration',1);
INSERT INTO tblAwardCategoryDesc VALUES (120,'Best Makeup',1);
INSERT INTO tblAwardCategoryDesc VALUES (121,'Best Music, Original Dramatic Score',1);
INSERT INTO tblAwardCategoryDesc VALUES (122,'Best Picture',1);
INSERT INTO tblAwardCategoryDesc VALUES (123,'Best Writing, Screenplay Written Directly for the Screen',1);

PAUSE Award category data complete... Press [Enter]

INSERT INTO tblAwardResult VALUES (1,'Won');
INSERT INTO tblAwardResult VALUES (2,'Nominated');

PAUSE Award result type data complete... Press [Enter]

INSERT INTO tblDirector VALUES (1,'Pierre','Morel');
INSERT INTO tblDirector VALUES (2,'Ruben','Fleischer');
INSERT INTO tblDirector VALUES (3,'Julian','Gilbey');
INSERT INTO tblDirector VALUES (4,'Timur','Bekmambetoy');
INSERT INTO tblDirector VALUES (5,'Mike','McCoy');
INSERT INTO tblDirector VALUES (6,'Scott','Waugh');
INSERT INTO tblDirector VALUES (7,'Joe','Johnston');
INSERT INTO tblDirector VALUES (8,'Olivier','Megaton');
INSERT INTO tblDirector VALUES (9,'Shawn','Levy');
INSERT INTO tblDirector VALUES (10,'Neil','Marshall');
INSERT INTO tblDirector VALUES (11,'Baltasar','Kormakur');
INSERT INTO tblDirector VALUES (12,'Patrick','Lussier');
INSERT INTO tblDirector VALUES (13,'Steven','Spielberg');

PAUSE Director data complete... Press [Enter]

INSERT INTO tblMPAA VALUES (1,'G','General Audiences. All Ages Admitted');
INSERT INTO tblMPAA VALUES (2,'PG','Parental Guidance Suggested. Some Material May Not Be Suitable For Children');
INSERT INTO tblMPAA VALUES (3,'PG-13','Parents Strongly Cautioned. Some Material May Be Inappropriate For Children Under 13');
INSERT INTO tblMPAA VALUES (4,'R','Restricted. Children Under 17 Require Accompanying Parent or Adult Guardian');
INSERT INTO tblMPAA VALUES (5,'NC-17','No One 17 and Under Admitted');

PAUSE MPAA data complete... Press [Enter]

INSERT INTO tblWriter VALUES (1,'Ben','Hecht');
INSERT INTO tblWriter VALUES (2,'Christopher','Nolan');
INSERT INTO tblWriter VALUES (3,'Walon','Green');
INSERT INTO tblWriter VALUES (4,'Sam','Peckinpah');
INSERT INTO tblWriter VALUES (5,'Nunnally','Johnson');
INSERT INTO tblWriter VALUES (6,'Frank S.','Nugent');
INSERT INTO tblWriter VALUES (7,'Sidney','Carroll');
INSERT INTO tblWriter VALUES (8,'Robert','Rossen');
INSERT INTO tblWriter VALUES (9,'Woody','Allen');
INSERT INTO tblWriter VALUES (10,'Francis Ford','Coppola');
INSERT INTO tblWriter VALUES (11,'Edmund H.','North');
INSERT INTO tblWriter VALUES (12,'Joseph','Stefano');
INSERT INTO tblWriter VALUES (13,'David','Mamet');
INSERT INTO tblWriter VALUES (14,'Alexander','Payne');
INSERT INTO tblWriter VALUES (15,'Jim','Taylor');
INSERT INTO tblWriter VALUES (16,'Eric','Roth');
INSERT INTO tblWriter VALUES (17,'Phil Alden','Robinson');
INSERT INTO tblWriter VALUES (18,'Federico','Fellini');
INSERT INTO tblWriter VALUES (19,'Brunello','Rondi');
INSERT INTO tblWriter VALUES (20,'Tullio','Pinelli');
INSERT INTO tblWriter VALUES (21,'Ennio','Flaiano');
INSERT INTO tblWriter VALUES (22,'Colin','Higgins');
INSERT INTO tblWriter VALUES (23,'Jean','Renoir');
INSERT INTO tblWriter VALUES (24,'Charles','Spaak');
INSERT INTO tblWriter VALUES (25,'William','Goldman');
INSERT INTO tblWriter VALUES (26,'John Michael','Hayes');
INSERT INTO tblWriter VALUES (27,'Donn','Pearce');
INSERT INTO tblWriter VALUES (28,'Frank','Pierson');
INSERT INTO tblWriter VALUES (29,'Jerzy','Kosinski');
INSERT INTO tblWriter VALUES (30,'Earl W.','Wallace');
INSERT INTO tblWriter VALUES (31,'William','Kelley');
INSERT INTO tblWriter VALUES (32,'Mel','Brooks');
INSERT INTO tblWriter VALUES (33,'Sylvester','Stallone');
INSERT INTO tblWriter VALUES (34,'Charlie','Kaufman');
INSERT INTO tblWriter VALUES (35,'Donald','Kaufman');
INSERT INTO tblWriter VALUES (36,'Paul','Schrader');
INSERT INTO tblWriter VALUES (37,'Mardik','Martin');
INSERT INTO tblWriter VALUES (38,'Carl','Foreman');
INSERT INTO tblWriter VALUES (39,'George','Lucas');
INSERT INTO tblWriter VALUES (40,'Cameron','Crowe');
INSERT INTO tblWriter VALUES (41,'Betty','Comden');
INSERT INTO tblWriter VALUES (42,'Adolph','Green');
INSERT INTO tblWriter VALUES (43,'James L.','Brooks');
INSERT INTO tblWriter VALUES (44,'Peter','Benchley');
INSERT INTO tblWriter VALUES (45,'Carl','Gottlieb');
INSERT INTO tblWriter VALUES (46,'Ted','Tally');
INSERT INTO tblWriter VALUES (47,'Robert','Zemeckis');
INSERT INTO tblWriter VALUES (48,'Bob','Gale');
INSERT INTO tblWriter VALUES (49,'Luc','Besson');
INSERT INTO tblWriter VALUES (50,'Robert Mark','Kamen');
INSERT INTO tblWriter VALUES (51,'Michael','Diliberti');
INSERT INTO tblWriter VALUES (52,'Julian','Gilbey');
INSERT INTO tblWriter VALUES (53,'Will','Gilbey');
INSERT INTO tblWriter VALUES (54,'Seth','Grahame-Smith');
INSERT INTO tblWriter VALUES (55,'Kurt','Johnstad');
INSERT INTO tblWriter VALUES (56,'Christopher','Marcus');
INSERT INTO tblWriter VALUES (57,'Josh','Klausner');
INSERT INTO tblWriter VALUES (58,'Robert','Rodat');

PAUSE Writer data complete... Press [Enter]

INSERT INTO tblActor VALUES (856,'Tracy','Nelson','F');
INSERT INTO tblActor VALUES (1101,'Maggie','Grace','F');
INSERT INTO tblActor VALUES (1102,'Famke','Janssen','F');
INSERT INTO tblActor VALUES (1105,'Nick','Swardson','M');
INSERT INTO tblActor VALUES (1103,'Jesse','Eisenberg','M');
INSERT INTO tblActor VALUES (1104,'Danny','McBride','M');
INSERT INTO tblActor VALUES (1106,'Alec','Newman','M');
INSERT INTO tblActor VALUES (1107,'Ed','Speleers','M');
INSERT INTO tblActor VALUES (1108,'Melissa','George','F');
INSERT INTO tblActor VALUES (1109,'Benjamin','Walker','M');
INSERT INTO tblActor VALUES (1110,'Rufus','Sewell','M');
INSERT INTO tblActor VALUES (1111,'Dominic','Cooper','M');
INSERT INTO tblActor VALUES (1113,'Alex','Veadov','M');
INSERT INTO tblActor VALUES (1112,'Roselyn','Sanchez','F');
INSERT INTO tblActor VALUES (1114,'Nestor','Serrano','M');
INSERT INTO tblActor VALUES (1115,'Chris','Evans','M');
INSERT INTO tblActor VALUES (1116,'Hugo','Weaving','M');
INSERT INTO tblActor VALUES (193,'Samuel L.','Jackson','M');
INSERT INTO tblActor VALUES (261,'Liam','Neeson','M');
INSERT INTO tblActor VALUES (1117,'Steve','Carell','M');
INSERT INTO tblActor VALUES (1119,'Mark','Wahlberg','M');
INSERT INTO tblActor VALUES (1118,'Tina','Fey','F');
INSERT INTO tblActor VALUES (54,'Nicolas','Cage','M');
INSERT INTO tblActor VALUES (1121,'William','Fichtner','M');
INSERT INTO tblActor VALUES (1120,'Amber','Heard','F');
INSERT INTO tblActor VALUES (168,'Tom','Hanks','M');
INSERT INTO tblActor VALUES (97,'Matt','Damon','M');
INSERT INTO tblActor VALUES (1122,'Tom','Sizemore','M');

PAUSE Actor data complete... Press [Enter]

INSERT INTO tblMovie VALUES (10,'Date Night',88,2010,'',9,3);
INSERT INTO tblMovie VALUES (36,'30 Minutes or Less',83,2011,'',2,4);
INSERT INTO tblMovie VALUES (37,'Captain America: The First Avenger',124,2011,'',7,3);
INSERT INTO tblMovie VALUES (41,'Drive Angry',104,2011,'','',4);
INSERT INTO tblMovie VALUES (48,'A Lonely Place to Die',99,2011,'',3,4);
INSERT INTO tblMovie VALUES (59,'Abraham Lincoln: Vampire Hunter',105,2012,'',4,4);
INSERT INTO tblMovie VALUES (60,'Act of Valor',110,2012,'',5,4);
INSERT INTO tblMovie VALUES (70,'Taken 2',92,2012,'',8,3);
INSERT INTO tblMovie VALUES (72,'Taken',93,2008,'',1,3);
INSERT INTO tblMovie VALUES (73,'Saving Private Ryan',169,1998,'',13,4);

PAUSE Movie title data complete... Press [Enter]

INSERT INTO tblActorDetail VALUES (10,1117);
INSERT INTO tblActorDetail VALUES (10,1118);
INSERT INTO tblActorDetail VALUES (10,1119);
INSERT INTO tblActorDetail VALUES (36,1103);
INSERT INTO tblActorDetail VALUES (36,1104);
INSERT INTO tblActorDetail VALUES (36,1105);
INSERT INTO tblActorDetail VALUES (37,193);
INSERT INTO tblActorDetail VALUES (37,1115);
INSERT INTO tblActorDetail VALUES (37,1116);
INSERT INTO tblActorDetail VALUES (41,54);
INSERT INTO tblActorDetail VALUES (41,1120);
INSERT INTO tblActorDetail VALUES (41,1121);
INSERT INTO tblActorDetail VALUES (48,1106);
INSERT INTO tblActorDetail VALUES (48,1107);
INSERT INTO tblActorDetail VALUES (48,1108);
INSERT INTO tblActorDetail VALUES (59,1109);
INSERT INTO tblActorDetail VALUES (59,1110);
INSERT INTO tblActorDetail VALUES (59,1111);
INSERT INTO tblActorDetail VALUES (60,1112);
INSERT INTO tblActorDetail VALUES (60,1113);
INSERT INTO tblActorDetail VALUES (60,1114);
INSERT INTO tblActorDetail VALUES (70,261);
INSERT INTO tblActorDetail VALUES (70,1101);
INSERT INTO tblActorDetail VALUES (70,1102);
INSERT INTO tblActorDetail VALUES (72,261);
INSERT INTO tblActorDetail VALUES (72,1101);
INSERT INTO tblActorDetail VALUES (72,1102);
INSERT INTO tblActorDetail VALUES (73,97);
INSERT INTO tblActorDetail VALUES (73,168);
INSERT INTO tblActorDetail VALUES (73,1122);

PAUSE Actor detail data complete... Press [Enter]

INSERT INTO tblWriterDetail VALUES (10,57);
INSERT INTO tblWriterDetail VALUES (36,51);
INSERT INTO tblWriterDetail VALUES (37,56);
INSERT INTO tblWriterDetail VALUES (48,52);
INSERT INTO tblWriterDetail VALUES (48,53);
INSERT INTO tblWriterDetail VALUES (59,54);
INSERT INTO tblWriterDetail VALUES (60,55);
INSERT INTO tblWriterDetail VALUES (70,49);
INSERT INTO tblWriterDetail VALUES (72,49);
INSERT INTO tblWriterDetail VALUES (72,50);
INSERT INTO tblWriterDetail VALUES (73,58);

PAUSE Writer detail data complete... Press [Enter]

INSERT INTO tblGenreDetail VALUES (10,2);
INSERT INTO tblGenreDetail VALUES (10,9);
INSERT INTO tblGenreDetail VALUES (10,20);
INSERT INTO tblGenreDetail VALUES (36,1);
INSERT INTO tblGenreDetail VALUES (36,2);
INSERT INTO tblGenreDetail VALUES (36,9);
INSERT INTO tblGenreDetail VALUES (37,1);
INSERT INTO tblGenreDetail VALUES (37,6);
INSERT INTO tblGenreDetail VALUES (37,8);
INSERT INTO tblGenreDetail VALUES (41,1);
INSERT INTO tblGenreDetail VALUES (41,9);
INSERT INTO tblGenreDetail VALUES (41,10);
INSERT INTO tblGenreDetail VALUES (41,21);
INSERT INTO tblGenreDetail VALUES (48,8);
INSERT INTO tblGenreDetail VALUES (48,9);
INSERT INTO tblGenreDetail VALUES (48,21);
INSERT INTO tblGenreDetail VALUES (59,1);
INSERT INTO tblGenreDetail VALUES (59,10);
INSERT INTO tblGenreDetail VALUES (59,11);
INSERT INTO tblGenreDetail VALUES (60,1);
INSERT INTO tblGenreDetail VALUES (60,7);
INSERT INTO tblGenreDetail VALUES (60,8);
INSERT INTO tblGenreDetail VALUES (60,21);
INSERT INTO tblGenreDetail VALUES (70,1);
INSERT INTO tblGenreDetail VALUES (70,9);
INSERT INTO tblGenreDetail VALUES (70,21);
INSERT INTO tblGenreDetail VALUES (72,1);
INSERT INTO tblGenreDetail VALUES (72,9);
INSERT INTO tblGenreDetail VALUES (72,21);
INSERT INTO tblGenreDetail VALUES (73,1);
INSERT INTO tblGenreDetail VALUES (73,7);
INSERT INTO tblGenreDetail VALUES (73,22);

PAUSE Genre detail data complete... Press [Enter]

INSERT INTO tblReview VALUES (1,'',7,5,72);
INSERT INTO tblReview VALUES (2,'',9,7,72);
INSERT INTO tblReview VALUES (3,'',6,26,72);
INSERT INTO tblReview VALUES (4,'',8,15,72);
INSERT INTO tblReview VALUES (5,'',7,22,72);
INSERT INTO tblReview VALUES (6,'',8,36,72);
INSERT INTO tblReview VALUES (7,'',9,24,72);
INSERT INTO tblReview VALUES (8,'',5,33,72);
INSERT INTO tblReview VALUES (9,'',6,2,72);
INSERT INTO tblReview VALUES (10,'',6,34,72);
INSERT INTO tblReview VALUES (11,'',8,29,72);
INSERT INTO tblReview VALUES (12,'',9,12,72);
INSERT INTO tblReview VALUES (13,'',6,27,72);
INSERT INTO tblReview VALUES (14,'',7,31,72);
INSERT INTO tblReview VALUES (15,'',3,32,72);
INSERT INTO tblReview VALUES (16,'',5,3,72);
INSERT INTO tblReview VALUES (17,'',8,10,72);
INSERT INTO tblReview VALUES (18,'',4,14,36);
INSERT INTO tblReview VALUES (19,'',2,8,36);
INSERT INTO tblReview VALUES (20,'',2,28,36);
INSERT INTO tblReview VALUES (21,'',6,24,36);
INSERT INTO tblReview VALUES (22,'',6,18,36);
INSERT INTO tblReview VALUES (23,'',3,15,36);
INSERT INTO tblReview VALUES (24,'',9,1,48);
INSERT INTO tblReview VALUES (25,'',8,5,48);
INSERT INTO tblReview VALUES (26,'',8,19,48);
INSERT INTO tblReview VALUES (27,'',10,25,48);
INSERT INTO tblReview VALUES (28,'',8,21,48);
INSERT INTO tblReview VALUES (29,'',8,23,48);
INSERT INTO tblReview VALUES (30,'',10,34,48);
INSERT INTO tblReview VALUES (31,'',6,3,70);
INSERT INTO tblReview VALUES (32,'',7,4,70);
INSERT INTO tblReview VALUES (33,'',5,8,70);
INSERT INTO tblReview VALUES (34,'',6,11,70);
INSERT INTO tblReview VALUES (35,'',7,18,70);
INSERT INTO tblReview VALUES (36,'',7,10,70);
INSERT INTO tblReview VALUES (37,'',5,29,70);
INSERT INTO tblReview VALUES (38,'',3,32,70);
INSERT INTO tblReview VALUES (39,'',6,23,70);
INSERT INTO tblReview VALUES (40,'',4,36,70);

PAUSE Review data complete... Press [Enter]

INSERT INTO tblAwardDetail VALUES (10,23,2,2010);
INSERT INTO tblAwardDetail VALUES (10,24,1,2010);
INSERT INTO tblAwardDetail VALUES (10,108,2,2011);
INSERT INTO tblAwardDetail VALUES (10,109,2,2011);
INSERT INTO tblAwardDetail VALUES (10,110,2,2011);
INSERT INTO tblAwardDetail VALUES (37,35,2,2012);
INSERT INTO tblAwardDetail VALUES (37,39,2,2012);
INSERT INTO tblAwardDetail VALUES (37,43,2,2012);
INSERT INTO tblAwardDetail VALUES (37,45,2,2012);
INSERT INTO tblAwardDetail VALUES (37,50,2,2012);
INSERT INTO tblAwardDetail VALUES (37,51,2,2012);
INSERT INTO tblAwardDetail VALUES (37,53,2,2012);
INSERT INTO tblAwardDetail VALUES (37,55,2,2012);
INSERT INTO tblAwardDetail VALUES (37,58,1,2012);
INSERT INTO tblAwardDetail VALUES (37,97,2,2012);
INSERT INTO tblAwardDetail VALUES (37,98,2,2012);
INSERT INTO tblAwardDetail VALUES (37,99,2,2012);
INSERT INTO tblAwardDetail VALUES (37,100,2,2011);
INSERT INTO tblAwardDetail VALUES (37,101,2,2012);
INSERT INTO tblAwardDetail VALUES (37,102,2,2011);
INSERT INTO tblAwardDetail VALUES (37,103,2,2011);
INSERT INTO tblAwardDetail VALUES (37,105,1,2012);
INSERT INTO tblAwardDetail VALUES (37,106,2,2012);
INSERT INTO tblAwardDetail VALUES (37,107,2,2012);
INSERT INTO tblAwardDetail VALUES (41,111,2,2012);
INSERT INTO tblAwardDetail VALUES (41,112,2,2012);
INSERT INTO tblAwardDetail VALUES (48,62,1,2011);
INSERT INTO tblAwardDetail VALUES (48,73,1,2011);
INSERT INTO tblAwardDetail VALUES (48,92,1,2011);
INSERT INTO tblAwardDetail VALUES (48,93,1,2011);
INSERT INTO tblAwardDetail VALUES (48,94,1,2011);
INSERT INTO tblAwardDetail VALUES (60,10,2,2012);
INSERT INTO tblAwardDetail VALUES (60,95,2,2012);
INSERT INTO tblAwardDetail VALUES (60,96,2,2012);
INSERT INTO tblAwardDetail VALUES (72,10,2,2009);
INSERT INTO tblAwardDetail VALUES (72,56,2,2010);
INSERT INTO tblAwardDetail VALUES (72,58,1,2009);
INSERT INTO tblAwardDetail VALUES (73,42,1,1999);
INSERT INTO tblAwardDetail VALUES (73,55,2,1999);
INSERT INTO tblAwardDetail VALUES (73,113,1,1999);
INSERT INTO tblAwardDetail VALUES (73,114,1,1999);
INSERT INTO tblAwardDetail VALUES (73,115,1,1999);
INSERT INTO tblAwardDetail VALUES (73,116,1,1999);
INSERT INTO tblAwardDetail VALUES (73,117,1,1999);
INSERT INTO tblAwardDetail VALUES (73,118,2,1999);
INSERT INTO tblAwardDetail VALUES (73,119,2,1999);
INSERT INTO tblAwardDetail VALUES (73,120,2,1999);
INSERT INTO tblAwardDetail VALUES (73,121,2,1999);
INSERT INTO tblAwardDetail VALUES (73,122,2,1999);
INSERT INTO tblAwardDetail VALUES (73,123,2,1999);

PAUSE Award detail data complete... Press [Enter]

INSERT INTO tblKeywordDetail VALUES (36,11);
INSERT INTO tblKeywordDetail VALUES (36,12);
INSERT INTO tblKeywordDetail VALUES (36,13);
INSERT INTO tblKeywordDetail VALUES (36,14);
INSERT INTO tblKeywordDetail VALUES (41,1);
INSERT INTO tblKeywordDetail VALUES (41,2);
INSERT INTO tblKeywordDetail VALUES (41,3);
INSERT INTO tblKeywordDetail VALUES (41,4);
INSERT INTO tblKeywordDetail VALUES (41,5);
INSERT INTO tblKeywordDetail VALUES (72,6);
INSERT INTO tblKeywordDetail VALUES (72,7);
INSERT INTO tblKeywordDetail VALUES (72,8);
INSERT INTO tblKeywordDetail VALUES (72,9);
INSERT INTO tblKeywordDetail VALUES (72,10);
INSERT INTO tblKeywordDetail VALUES (73,8);
INSERT INTO tblKeywordDetail VALUES (73,15);
INSERT INTO tblKeywordDetail VALUES (73,16);
INSERT INTO tblKeywordDetail VALUES (73,17);

PAUSE Keyword detail data complete... Press [Enter]
COMMIT;